import type { Metadata } from 'next';
import { Locale, i18n } from '@/i18n.config';
import { Inter } from 'next/font/google';
import './globals.css';
import PublicNavbar from './_components/PublicNavbar';
import { getDictionary } from '@/lib/dictionary';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export async function generateStaticParams() {
	return i18n.locales.map((locale: any) => ({ lang: locale }));
}

export default async function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { lang: Locale };
}) {
	console.log('RootLayout---------params', params);
	const dictionary = await getDictionary(params?.lang);
	return (
		<html lang={params.lang}>
			<body className={inter.className}>
				<div className='w-[70%] mx-auto my-0 relative'>
					<PublicNavbar
						lang={params?.lang}
						dictionary={dictionary}
					/>
					<main className='mt-[80px] py-[60px]'>{children}</main>
				</div>
			</body>
		</html>
	);
}
